config/routes.rb
Rails.application.routes.draw do
  resources :labels
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  root to: 'tasks#index'
  resources :users
  namespace :admin do
    resources :users
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :tasks, dependent: :destroy
  before_destroy :destroy_action
  before_update :update_action

  private

  def destroy_action
    if User.where(admin: true).count == 1 && self.admin == true
      throw :abort
    end
  end
  
  def update_action
    if User.where(admin: true).count == 1 && self.admin == false
      throw :abort
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :admin_login_required
  skip_before_action :login_required, only: [:new, :create]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザーを作成しました"
    else
      render :new
    end
  end

  def index
    @users = User.select(:id, :name, :email, :admin)
  end

  def show
    @tasks = @user.tasks.all
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザーを編集しました！"
    else
      render :edit, notice: "ユーザーの情報を更新できません"
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザーを削除しました！"
    else
      redirect_to admin_users_path, notice: "管理者がいなくなるので削除できません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :logged_in, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to user_path(@user.id), notice: "登録しました"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to tasks_path, notice: "他人の情報にはアクセスできません"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :admin)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>ユーザーを編集する</h2>

<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="user_id">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
    <div class="user_id">
    <%= form.label :管理者権限 %>
    <%= form.check_box :admin %>
  </div>
  <div class="user_id">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div class="user_id">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div class="user_id">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>
    
  <%= form.submit "Edit this account" %>
<% end %>

<br>
<%= link_to "ユーザー一覧画面にもどる", admin_users_path %>

app/views/admin/users/index.html.erb
<h1>管理画面のユーザー一覧画面</h1>

<table>
  <tr>
    <th>ユーザーID</th>
    <th>ユーザー名</th>
    <th>メールアドレス</th>
    <th>管理者権限</th>
    <th>タスク数</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.admin %></td>
    <td><%= user.tasks.count %></td>
    <td><%= link_to '詳細', admin_user_path(user), class: "btn btn-primary" %></td>
    <td><%= link_to '編集', edit_admin_user_path(user), class: "btn btn-warning" %></td>
    <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<p><%= link_to "新規ユーザー登録", new_admin_user_path%></p>

app/views/admin/users/new.html.erb
<h1>管理画面のユーザー作成画面</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :管理者権限 %>
  <%= f.check_box :admin %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create this account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<p>管理者権限: <%= @user.admin %></p>

<h2>タスク一覧</h2>
<table>
  <tr>
    <th>作成者</th>
    <th>タスク名</th>
    <th>タスク詳細</th>
    <th>終了期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
  </tr>

  <% @user.tasks.each do |task| %>
    <tr>
      <td><%= task.user.name %></td>
      <td><%= task.title %></td>
      <td><%= task.content %></td>
      <td><%= task.deadline %></td>
      <td><%= task.status %></td>
      <td><%= task.priority %></td>
      <td><%= link_to '詳細', task_path(task.id) %></td>
      <td><%= link_to '編集', edit_task_path(task.id) %></td>
      <td><%= link_to '削除', task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'ユーザー一覧画面へ戻る', admin_users_path %>